There is no link between mobile phones and any health problems, a decade-long report has concluded.

The study also found no evidence that exposure to base station emissions during pregnancy increases the risk of childhood leukaemia.

The Mobile Telecommunications and Health
 Research programme was the UK’s largest research programme to look at 
the possible health risks associated with mobile phone technology.

There is no link between mobile phone use and cancer, new research suggests

Professor David Coggon, Chairman of MTHR, said: ‘When the MTHR programme was first set up, there were many scientific uncertainties about possible health risks from mobile phones and related technology. 

‘This independent programme is now complete, and despite exhaustive research, we have found no evidence of risks to health from the radio waves produced by mobile phones or their base stations.

‘Thanks to the research conducted within the programme, we can now be much more confident about the safety of modern telecommunications systems.’

The £13.6 million, 11 year programme has been jointly funded by the UK government and the telecommunications industry. 

Its findings support 2012 research which showed mobile and Wi-Fi technology doesn't cause cancer and causes no damage to health.

There is also no link between exposure to power lines during pregnancy and childhood leukaemia

After assessing health hazards from low-level electromagnetic fields generated by radio transmitters, researchers at the Norwegian Expert Committee found there is no scientific evidence that exposure  poses a health risk.

These electromagnetic fields are found around mobile phones, wireless phones and networks, mobile phone base stations, broadcasting transmitters and other communications equipment.

The latest research also supports a 2011 study from Imperial College London which found that living close to a mobile phone mast does not increase a child's chance of developing a brain tumour or a tumour of the central nervous system.

In 2011 the WHO suggested that people try to text rather than making phone calls to reduce their chance of developing a brain tumour from phone use

Study author Professor Paul Elliott of Imperial College London, said: 'People are worried that living near a mobile phone mast might affect their children's health.

'We looked at this question with respect to risk of cancers in young children.

'We found no pattern to suggest that the children of mums living near a base station during pregnancy had a greater risk of developing cancer than those who lived elsewhere.'

Research released just last week also revealed that children who live near overhead power lines do not have an increased risk of leukaemia.

The University of Oxford researchers studied 16,500 children with the cancer in the UK and found living near power lines did not increase risk of the disease.

Despite all of this evidence, some people may remain unconvinced.

In 2011 the World Health Organisation warned mobile phone users to limit their use of the devices as they could cause cancer.

The WHO suggested people use hands-free kits and that they text people instead of calling them to reduce their exposure to the phone.

The comments were made after earlier research which suggested that just half an hour's mobile phone use a day could increase the risk of a brain tumour by 40 per cent.

@highlight

There is 'no evidence' to suggest that exposure to base station emissions during pregnancy increases the risk of childhood leukaemia

@highlight

There is also no evidence that shows they cause any other health problems

@highlight

£13.6 million, 11 year programme has been jointly funded by the UK government and the telecommunications industry